"""Validate the animation reference library and regenerate its index and pattern-card evidence.

Usage:
  python3 tools/ref_index.py [--check] [--prune]

  (no flags)  validate every references/videos/<slug>/, write references/index.json, create a stub card
              references/patterns/<id>.md for every registry ID without one, and rewrite the generated
              evidence block of every card (the hand-written quality bar is never touched)
  --prune     first delete stills of reviewed face/other shots and stills no shot references
  --check     write nothing; exit 1 on any invalid video, draft shot, stills budget overrun, stale index or
              stale card. Cards whose quality bar is not written yet are warnings.
Pattern IDs come from standards/formats/long-form.md (tools/refs.py).

Run with no flags to regenerate; --help prints this help; any unknown flag prints it and exits 2.
"""
import json
import statistics
import sys
from pathlib import Path

import refs

ROOT = refs.ROOT
MAX_TABLE = 8


def _ts(t: float) -> str:
    m, s = divmod(t, 60)
    return f"{int(m)}:{s:04.1f}"


def _median(values):
    vals = [v for v in values if isinstance(v, (int, float))]
    return round(statistics.median(vals), 2) if vals else None


def _spread(values):
    vals = sorted(v for v in values if isinstance(v, (int, float)))
    if len(vals) < 4:
        return None
    q = statistics.quantiles(vals, n=4)
    return [round(q[0], 2), round(q[2], 2)]


def _stats(hits) -> dict:
    durs = [s["t_out"] - s["t_in"] for _, s in hits]
    return {"count": len(hits), "videos": len({v["source"]["slug"] for v, _ in hits}),
            "duration_median": _median(durs), "duration_p25_p75": _spread(durs),
            "type_px_median": _median([(s.get("layout") or {}).get("type_px") for _, s in hits]),
            "word_rate_s_median": _median([(s.get("motion") or {}).get("word_rate_s") for _, s in hits]),
            "hold_s_median": _median([(s.get("motion") or {}).get("hold_s") for _, s in hits])}


def card_status(text: str) -> str:
    head = text.split(refs.GEN_START)[0]
    bar = head.split("## Quality bar", 1)[1] if "## Quality bar" in head else ""
    return "ready" if bar.strip() and refs.STUB not in bar else "draft"


def _card_path(root, pid) -> Path:
    return Path(root) / "references" / "patterns" / f"{pid}.md"


def build_index(lib: dict, root=ROOT) -> dict:
    videos = []
    for v in lib["videos"]:
        src, shots = v["source"], v["shots"]
        graphic = sum(s["t_out"] - s["t_in"] for s in shots if s.get("status") == "reviewed" and s.get("kind") == "graphic")
        videos.append({"slug": src["slug"], "title": src["title"], "ground": src["ground"], "format": src["format"],
                       "duration": src["duration"], "shots": len(shots),
                       "reviewed": sum(s.get("status") == "reviewed" for s in shots),
                       "graphics_pct": round(100 * graphic / src["duration"], 1),
                       "stills_bytes": sum(p.stat().st_size for p in (v["dir"] / "stills").glob("*"))})
    patterns = {}
    for pid, info in sorted(lib["registry"].items()):
        hits = refs.exemplars(lib, pid)
        card = _card_path(root, pid)
        patterns[pid] = {"name": info["name"], "group": info["group"],
                         "card": card_status(card.read_text()) if card.is_file() else "draft",
                         "exemplars": [{"video": v["source"]["slug"], "shot": s["id"], "t_in": s["t_in"],
                                        "t_out": s["t_out"], "stills": s["stills"]} for v, s in hits],
                         "stats": _stats(hits)}
    candidates = {}
    for v in lib["videos"]:
        for s in v["shots"]:
            p = s.get("pattern")
            if s.get("status") == "reviewed" and isinstance(p, str) and p.startswith(refs.NEW_PREFIX):
                candidates.setdefault(p, []).append({"video": v["source"]["slug"], "shot": s["id"]})
    return {"videos": videos, "patterns": patterns, "candidates": dict(sorted(candidates.items()))}


def evidence_block(lib: dict, pid: str) -> str:
    hits = refs.exemplars(lib, pid)
    st = _stats(hits)
    lines = [refs.GEN_START, "## Evidence (generated by tools/ref_index.py — do not edit)", ""]
    if not hits:
        lines += ["No reviewed reference shot uses this pattern yet.", refs.GEN_END]
        return "\n".join(lines)
    noun = "exemplar" if st["count"] == 1 else "exemplars"
    vids = "video" if st["videos"] == 1 else "videos"
    facts = [f"**{st['count']} {noun}** from {st['videos']} {vids}",
             f"duration median {st['duration_median']} s" + (f" (p25–p75 {st['duration_p25_p75'][0]}–{st['duration_p25_p75'][1]} s)" if st["duration_p25_p75"] else "")]
    if st["type_px_median"] is not None:
        facts.append(f"largest text median {st['type_px_median']} px at 1080")
    if st["word_rate_s_median"] is not None:
        facts.append(f"word build {st['word_rate_s_median']} s/word")
    if st["hold_s_median"] is not None:
        facts.append(f"hold {st['hold_s_median']} s")
    lines += [" · ".join(facts), "", "| Video | Time | Stills | Why it works |", "|---|---|---|---|"]
    for v, s in hits[:MAX_TABLE]:
        slug = v["source"]["slug"]
        pick = list(dict.fromkeys([s["stills"][len(s["stills"]) // 2], s["stills"][-1]]))
        imgs = " ".join(f"![{slug} {s['id']}](../videos/{slug}/{p})" for p in pick)
        why = " ".join(s.get("quality", "").split()).replace("|", "\\|")
        star = " ★" if s.get("exemplar") else ""
        lines.append(f"| {slug} {s['id']}{star} | {_ts(s['t_in'])}–{_ts(s['t_out'])} | {imgs} | {why} |")
    if len(hits) > MAX_TABLE:
        lines.append(f"\n…and {len(hits) - MAX_TABLE} more in references/index.json.")
    lines.append(refs.GEN_END)
    return "\n".join(lines)


def stub_card(pid: str, info: dict) -> str:
    return (f"---\nid: {pid}\nname: {info['name']}\ngroup: {info['group']}\n---\n"
            f"# {pid} — {info['name']}\n\n"
            f"Rule: `standards/formats/long-form.md` ({'kit table' if info['group'] == 'kit' else f'catalogue row {pid}'}). "
            "This card holds the evidence and the quality bar; the rule stays in the format profile.\n\n"
            f"## Quality bar\n\n{refs.STUB} — write it from the exemplars below (references/README.md §Quality bar)._\n\n"
            f"{refs.GEN_START}\n{refs.GEN_END}\n")


def _with_block(text: str, block: str, path: Path) -> str:
    if refs.GEN_START not in text or refs.GEN_END not in text:
        raise refs.RefError(f"{path}: missing {refs.GEN_START} / {refs.GEN_END} markers — restore them")
    head, rest = text.split(refs.GEN_START, 1)
    tail = rest.split(refs.GEN_END, 1)[1]
    return head + block + tail


def prune(root=ROOT) -> int:
    removed = 0
    reg = refs.registry(root)
    for d in refs.video_dirs(root):
        if refs.validate_video(d, reg):    # malformed or invalid: never touch it, --check reports why
            continue
        path = d / "shots.json"
        data = json.loads(path.read_text())
        keep = set()
        for s in data["shots"]:
            if s.get("status") == "reviewed" and s.get("kind") in ("face", "other") and s.get("stills"):
                for p in s["stills"]:
                    if refs.STILL_PATH.fullmatch(p):
                        (d / p).unlink(missing_ok=True)
                        removed += 1
                s["stills"] = []
            keep.update(s.get("stills") or [])
        for p in (d / "stills").glob("*"):
            if p.is_file() and f"stills/{p.name}" not in keep:
                p.unlink()
                removed += 1
        path.write_text(json.dumps(data, indent=2) + "\n")
    return removed


def run(root=ROOT, check=False):
    lib = refs.load_library(root)
    findings, warnings = list(lib["findings"]), []
    for v in lib["videos"]:
        slug = v["source"]["slug"]
        drafts = sum(s.get("status") == "draft" for s in v["shots"])
        if drafts:
            findings.append(f"{slug}: {drafts} draft shot{'s' if drafts > 1 else ''} — analyse them (references/README.md §Analyse)")
        faces = [s["id"] for s in v["shots"] if s.get("kind") in ("face", "other") and s.get("stills") and s.get("status") == "reviewed"]
        if faces:
            findings.append(f"{slug}: reviewed face/other shots still have stills ({', '.join(faces[:5])}…) — run --prune")
    index = build_index(lib, root)
    for row in index["videos"]:
        if row["stills_bytes"] > refs.STILLS_BUDGET:
            findings.append(f"{row['slug']}: stills are {row['stills_bytes'] / 1e6:.1f} MB, over the "
                            f"{refs.STILLS_BUDGET / 1e6:.0f} MB budget — drop stills of weak shots")
    want_index = json.dumps(index, indent=2) + "\n"
    index_path = Path(root) / "references" / "index.json"
    cards = {}
    for pid, info in lib["registry"].items():
        path = _card_path(root, pid)
        text = path.read_text() if path.is_file() else stub_card(pid, info)
        cards[path] = _with_block(text, evidence_block(lib, pid), path)
        if card_status(cards[path]) == "draft" and refs.exemplars(lib, pid):
            warnings.append(f"{pid}: quality bar not written yet ({len(refs.exemplars(lib, pid))} exemplars available)")
    if check:
        for card in sorted((Path(root) / "references" / "patterns").glob("*.md")):
            if card.stem not in lib["registry"]:
                findings.append(f"orphan pattern card {card.stem} — its catalogue row is gone; delete or restore the row")
        if not index_path.is_file() or index_path.read_text() != want_index:
            findings.append("references/index.json is stale — run python3 tools/ref_index.py")
        stale = [p.stem for p, t in cards.items() if not p.is_file() or p.read_text() != t]
        if stale:
            findings.append(f"pattern cards stale: {', '.join(sorted(stale))} — run python3 tools/ref_index.py")
        return findings, warnings
    index_path.parent.mkdir(parents=True, exist_ok=True)
    index_path.write_text(want_index)
    for path, text in cards.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(text)
    return findings, warnings


def main(argv, root=ROOT) -> int:
    args = argv[1:]
    if "--help" in args or "-h" in args:
        print(__doc__)
        return 0
    unknown = [a for a in args if a not in ("--check", "--prune")]
    if unknown:
        print(__doc__)
        return 2
    try:
        if "--prune" in args and "--check" not in args:
            print(f"pruned {prune(root)} still files")
        findings, warnings = run(root, check="--check" in args)
    except (refs.RefError, json.JSONDecodeError) as e:
        print(f"error: {e}")
        return 1
    for w in warnings:
        print(f"warning: {w}")
    for f in findings:
        print(f"- {f}")
    lib_videos = len(refs.video_dirs(root))
    print(("FAIL" if findings else "OK") + f" — {lib_videos} reference videos")
    return 1 if findings else 0


if __name__ == "__main__":
    sys.exit(main(sys.argv))
