"""The animation reference library — references/ (see references/README.md).

references/videos/<slug>/source.json + shots.json + stills/   one analysed reference video each
references/patterns/<id>.md                                   one card per pattern ID
references/index.json                                         generated by tools/ref_index.py

Pattern IDs come from standards/formats/long-form.md: the catalogue rows (A1–E2) and the kit table
(HFKit.title → "title", HFKit.lowerThird → "lower-third"). The rules stay there; this library is the
evidence. Standard library only.
"""
import json
import math
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
FORMATS = ("long-form", "shorts")
PLACEMENTS = ("full-frame", "over-footage")
KINDS = ("face", "graphic", "section", "other")
STATUSES = ("draft", "reviewed")
GROUNDS = ("dark", "light", "mixed")
FILLS = ("sparse", "balanced", "dense")
NEW_PREFIX = "new:"
STILLS_BUDGET = 10 * 1024 * 1024
GEN_START, GEN_END = "<!-- generated:start -->", "<!-- generated:end -->"
STUB = "_Not written yet"
CATALOGUE_ROW = re.compile(r"^\|\s*([A-E]\d)\s*\|\s*([^|]+?)\s*\|", re.M)
KIT_ROW = re.compile(r"^\|\s*`HFKit\.(\w+)`\s*\|", re.M)
ID_TOKEN = re.compile(r"(?<![\w-])([A-Z]\d{1,2})(?![\w-])")
WORD_TOKEN = re.compile(r"(?<![\w-])([a-z]+(?:-[a-z]+)*)(?![\w-])")
HEX = re.compile(r"#[0-9A-Fa-f]{6}")
SLUG = re.compile(r"[a-z0-9]+(?:-[a-z0-9]+)*")
SHOT_ID = re.compile(r"s\d{3,}")
DATE = re.compile(r"\d{4}-\d{2}-\d{2}")
SOURCE_KEYS = ("slug", "title", "url", "format", "ground", "made_by", "brand", "duration", "fps",
               "width", "height", "source_file", "ingested")


class RefError(Exception):
    """A reference file that is missing or cannot be parsed."""


def kebab(name: str) -> str:
    return re.sub(r"(?<!^)([A-Z])", r"-\1", name).lower()


def registry(root=ROOT) -> dict:
    """{id: {"name", "group"}} — catalogue/section IDs and kit components from the long-form profile."""
    text = (Path(root) / "standards" / "formats" / "long-form.md").read_text()
    reg = {}
    for m in CATALOGUE_ROW.finditer(text):
        pid = m.group(1)
        reg[pid] = {"name": m.group(2).strip("* ").strip(), "group": "section" if pid[0] == "E" else "custom"}
    for m in KIT_ROW.finditer(text):
        reg[kebab(m.group(1))] = {"name": f"HFKit.{m.group(1)}", "group": "kit"}
    return reg


def type_ids(cell: str, reg: dict):
    """Pattern IDs cited by a storyboard `type` cell: (known, unknown). Prose words are ignored;
    an ID-shaped token (letter + digits) that is not in the registry is unknown."""
    known, unknown = [], []
    for t in ID_TOKEN.findall(cell):
        (known if t in reg else unknown).append(t)
    known += [t for t in WORD_TOKEN.findall(cell) if t in reg and reg[t]["group"] == "kit"]
    return known, unknown


def empty_shot(i: int, t_in: float, t_out: float) -> dict:
    return {"id": f"s{i:03d}", "t_in": t_in, "t_out": t_out, "status": "draft", "kind": None, "pattern": None,
            "placement": None, "stills": [], "layout": None, "motion": None, "colours": [], "marks": [],
            "notes": "", "quality": ""}


def _num(v) -> bool:
    return isinstance(v, (int, float)) and not isinstance(v, bool) and math.isfinite(v)


def _read_json(path: Path, findings: list, label: str):
    if not path.is_file():
        findings.append(f"{label}: {path.name} not found")
        return None
    try:
        return json.loads(path.read_text())
    except json.JSONDecodeError as e:
        findings.append(f"{label}: {path.name} is not valid JSON ({e.msg} at line {e.lineno})")
        return None


def load_video(d) -> dict:
    d = Path(d)
    findings = []
    source = _read_json(d / "source.json", findings, d.name)
    shots = _read_json(d / "shots.json", findings, d.name)
    if findings:
        raise RefError("; ".join(findings))
    return {"dir": d, "source": source, "shots": shots.get("shots", []) if isinstance(shots, dict) else []}


def _check_source(src, d: Path) -> list:
    out = []
    if not isinstance(src, dict):
        return ["source.json: root must be an object"]
    missing = [k for k in SOURCE_KEYS if k not in src]
    if missing:
        out.append(f"source.json: missing {', '.join(missing)}")
    if src.get("slug") != d.name:
        out.append(f"source.json: slug {src.get('slug')!r} must equal the folder name {d.name!r}")
    if not SLUG.fullmatch(d.name):
        out.append(f"folder name {d.name!r} must be a kebab-case slug")
    if src.get("format") not in FORMATS:
        out.append(f"source.json: format must be one of {', '.join(FORMATS)}")
    if src.get("ground") not in GROUNDS:
        out.append(f"source.json: ground must be one of {', '.join(GROUNDS)}")
    for k in ("title", "made_by", "brand", "source_file"):
        if not (isinstance(src.get(k), str) and src.get(k).strip()):
            out.append(f"source.json: {k} must be a non-empty string")
    for k in ("duration", "fps"):
        if not (_num(src.get(k)) and src.get(k) > 0):
            out.append(f"source.json: {k} must be a positive number")
    for k in ("width", "height"):
        if not (isinstance(src.get(k), int) and src.get(k) > 0):
            out.append(f"source.json: {k} must be a positive integer")
    if not (isinstance(src.get("ingested"), str) and DATE.fullmatch(src["ingested"])):
        out.append("source.json: ingested must be YYYY-MM-DD")
    if "/" in str(src.get("source_file", "")):
        out.append("source.json: source_file is the file name only, never a path")
    return out


def _check_reviewed(s: dict, reg: dict, sid: str) -> list:
    out = []
    kind, pattern = s.get("kind"), s.get("pattern")
    if kind not in KINDS:
        return [f"{sid}: kind must be one of {', '.join(KINDS)}"]
    if kind in ("face", "other"):
        if pattern is not None:
            out.append(f"{sid}: a {kind} shot has no pattern (set null)")
        return out
    candidate = isinstance(pattern, str) and pattern.startswith(NEW_PREFIX) and SLUG.fullmatch(pattern[len(NEW_PREFIX):])
    if not (candidate or (isinstance(pattern, str) and pattern in reg)):
        out.append(f"{sid}: pattern {pattern!r} is not in the registry (an ID from standards/formats/long-form.md, or new:<slug>)")
    elif kind == "section" and not candidate and reg[pattern]["group"] != "section":
        out.append(f"{sid}: a section shot needs a section pattern (E1, E2 or new:<slug>), got {pattern}")
    if s.get("placement") not in PLACEMENTS:
        out.append(f"{sid}: placement must be full-frame or over-footage")
    if not (isinstance(s.get("quality"), str) and len(s["quality"].strip()) >= 20):
        out.append(f"{sid}: quality must say why the shot works (≥ 20 characters)")
    lay = s.get("layout")
    if not (isinstance(lay, dict) and isinstance(lay.get("type_px"), int) and lay["type_px"] >= 0
            and lay.get("fill") in FILLS and isinstance(lay.get("layers"), int) and lay["layers"] >= 1):
        out.append(f"{sid}: layout must be {{type_px: int ≥ 0, fill: {'|'.join(FILLS)}, layers: int ≥ 1}}")
    mo = s.get("motion")
    if not (isinstance(mo, dict) and isinstance(mo.get("entrance"), str) and mo["entrance"].strip()
            and isinstance(mo.get("camera"), str)
            and all(mo.get(k) is None or (_num(mo.get(k)) and mo[k] >= 0) for k in ("word_rate_s", "hold_s"))):
        out.append(f"{sid}: motion must be {{entrance: text, camera: text, word_rate_s: s|null, hold_s: s|null}}")
    if not (isinstance(s.get("colours"), list) and all(isinstance(c, str) and HEX.fullmatch(c) for c in s["colours"])):
        out.append(f"{sid}: colours must be a list of #RRGGBB")
    if not (isinstance(s.get("marks"), list) and all(isinstance(m, str) for m in s["marks"])):
        out.append(f"{sid}: marks must be a list of strings")
    if not s.get("stills"):
        out.append(f"{sid}: a reviewed {kind} shot keeps at least one still")
    return out


def validate_video(d, reg: dict) -> list:
    """Findings for one reference video folder; [] when valid. Never raises on bad content."""
    d = Path(d)
    label = f"references/videos/{d.name}"
    findings = []
    src = _read_json(d / "source.json", findings, label)
    data = _read_json(d / "shots.json", findings, label)
    if findings:
        return findings
    findings += [f"{label}/{f}" for f in _check_source(src, d)]
    shots = data.get("shots") if isinstance(data, dict) else None
    if not isinstance(shots, list) or not shots:
        return findings + [f"{label}/shots.json: needs a non-empty \"shots\" list"]
    fps = src.get("fps") if _num(src.get("fps")) and src.get("fps") > 0 else 30.0
    tol = 2 / fps + 1e-6
    seen, prev_out = set(), 0.0
    for i, s in enumerate(shots):
        sid = s.get("id") if isinstance(s, dict) else None
        where = f"{label}/shots.json {sid or f'#{i + 1}'}"
        if not isinstance(s, dict) or not (isinstance(sid, str) and SHOT_ID.fullmatch(sid)):
            findings.append(f"{where}: each shot is an object with an id like s001")
            continue
        if sid in seen:
            findings.append(f"{where}: duplicate id")
        seen.add(sid)
        a, b = s.get("t_in"), s.get("t_out")
        if not (_num(a) and _num(b) and b > a):
            findings.append(f"{where}: t_in/t_out must be numbers with t_out > t_in")
            continue
        if abs(a - prev_out) > tol:
            findings.append(f"{where}: starts at {a} but the previous shot ends at {prev_out}")
        prev_out = b
        if s.get("status") not in STATUSES:
            findings.append(f"{where}: status must be draft or reviewed")
        stills = s.get("stills")
        if not isinstance(stills, list):
            findings.append(f"{where}: stills must be a list")
            stills = []
        for p in stills:
            if not (isinstance(p, str) and p.startswith("stills/") and (d / p).is_file()):
                findings.append(f"{where}: still {p} not found")
        if s.get("status") == "reviewed":
            findings += [f"{label}/shots.json {f}" for f in _check_reviewed(s, reg, sid)]
        if s.get("exemplar") and s.get("kind") not in ("graphic", "section"):
            findings.append(f"{where}: only graphic or section shots can be exemplars")
    if _num(src.get("duration")) and abs(prev_out - src["duration"]) > tol:
        findings.append(f"{label}/shots.json: last shot ends at {prev_out} but the video lasts {src['duration']}")
    return findings


def video_dirs(root=ROOT) -> list:
    base = Path(root) / "references" / "videos"
    return sorted(p for p in base.iterdir() if p.is_dir() and (p / "source.json").is_file()) if base.is_dir() else []


def load_library(root=ROOT) -> dict:
    """Every valid video plus the findings of the invalid ones (which are left out of the library)."""
    reg = registry(root)
    videos, findings = [], []
    for d in video_dirs(root):
        f = validate_video(d, reg)
        if f:
            findings += f
            continue
        videos.append(load_video(d))
    return {"registry": reg, "videos": videos, "findings": findings}


def exemplars(lib: dict, pid: str) -> list:
    """Reviewed shots tagged `pid`: pinned exemplars first, then by video slug and time."""
    hits = [(v, s) for v in lib["videos"] for s in v["shots"]
            if s.get("status") == "reviewed" and s.get("pattern") == pid]
    return sorted(hits, key=lambda vs: (not vs[1].get("exemplar"), vs[0]["source"]["slug"], vs[1]["t_in"]))
